### ISSUE TITLE
Failed to install 

### ISSUE THREAD

**Issue by djoudi** [robinrmds/Notifier#1]
Fetching pfSense-pkg-Notifier-0.1_3.pkg: .. done
Installing pfSense-pkg-Notifier-0.1_3...
pkg: wrong architecture: FreeBSD:12:amd64 instead of FreeBSD:12:armv7

Failed to install the following 1 package(s): https://github.com/robinrmds/Notifier/raw/main/pfSense-pkg-Notifier-0.1_3.pkg

**Comment by djoudi** [comment]
@robinrmds

**Comment by robinrmds** [comment]
What hardware architecture are you using?

**Comment by robinrmds** [comment]
Is it possible to add the package manually.
To do this, just copy the files from the pfSense-pkg-Notifier folder as they are arranged there. And add the contents of the notifier.xml file in the config.xml file.

Here's an example:

	<installedpackages>
		<package>
			<name>Notifier</name>
			<descr><![CDATA[The Notifier utility is used to send realtime notifications to telegram.]]></descr>
			<version>0.1_4</version>
			<configurationfile>notifier.xml</configurationfile>
			<include_file>/usr/local/pkg/notifier.inc</include_file>
		</package>
		<menu>
			<name>Notifier</name>
			<section>Services</section>
			<configfile>notifier.xml</configfile>
			<url>/packages/notifier/notifier.php</url>
		</menu>
	</installedpackages>
